name: Tests

on:

  push:
    branches:
      - main
    paths-ignore:
      -'docs/**'
      -'sample_programs/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      -'docs/**'
      -'sample_programs/**'


jobs:
  Test:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - run:  git clone https://github.com/galloj/IFJ22_Tester.git


      - name: Build
        run: make


      - name: Python tests -without IFJcode interpreter
        run: |
          cd IFJ22_Tester
          ./test.py ../main

      - name: Python tests -with IFJcode interpreter
        if: success() || failure()
        run: |
          cd IFJ22_Tester
          ./test.py ../main ../ic22int
