name: Upload lints

on:
  workflow_run:
    workflows: ["Makefile CI"]
    branches: [main]
    types: [completed]

jobs:
  upload-sarif:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
      - run: cargo install clang-tidy-sarif sarif-fmt
      - run: make lint_pedantic --silent | clang-tidy-sarif > results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
